#!ruby
require 'curses'

str = `banner #{ARGV[0]}`

def render(str, col_offset)
  col = Curses.cols - str.each_line.max_by(&:size).size + col_offset
  line = (Curses.lines - str.each_line.count) / 2

  Curses.clear
  str.each_line.with_index do |str_line, index|
    Curses.setpos(line + index, [col, 0].max)
    str_line = str_line[-col..-1] || '' if col < 0
    Curses.addstr(str_line)
  end
  Curses.refresh
end

Curses.init_screen
begin
  Curses.cols.times do |idx|
    render(str, -idx)
    sleep 0.04
  end
ensure
  Curses.close_screen
end
